version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  app:
    build:
      context: .
    container_name: app
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db

    restart: always

volumes:
  postgres_data:
